### ISSUE TITLE
Highlight is not working in js

### ISSUE THREAD

**Issue by Paganus** [atom/language-todo#91] opened 2018-11-15 17:38 UTC
### Description
Highlight is not working in js files (JavaScript grammar selected). But it works in other files/grammars.

### Versions

Atom version 1.32.2
OS Linux Mint 19 Tara 

### Additional Information
Have tried a fresh install on other pc (thought the problem maybe with packages) - same problem.

**Comment by Arcanemagus** [comment] 2018-11-15 18:18
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-todo/issues/82. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-11-15 18:18 UTC
