### ISSUE TITLE
Stopped working even in safe mode

### ISSUE THREAD

**Issue by macdonaldtomw** [atom/language-todo#87] opened 2018-10-30 15:25 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Syntax highlighting and scope detection for the TODO keyword does not work anymore (not sure what changed).  

### Steps to Reproduce

1. Launch atom in safe mode
2. Create a new cpp file
3. Type in a comment with `TODO` in it
4. Watch in horror as nothing happens

**Expected behavior:** TODO gets highlighted.  If scope is checked on the TODO token, it should not say "comment block"

**Actual behavior:** TODO _does not_ get highlighted.  If scope is checked on the TODO token, it should not say "comment block"

**Reproduces how often:** 100% of time

### Versions

1.32.0

### Additional Information

See YouTube video of this:

https://www.youtube.com/watch?v=7YI3qwZWyTE&feature=youtu.be

**Comment by macdonaldtomw** [comment] 2018-10-30 15:29
Note:

If I do not comment the TODO, it correctly evaluates the scope of the TODO to `support.storage.type`

**Comment by Ben3eeE** [comment] 2018-10-30 15:34
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-todo/issues/82. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-10-30 15:34 UTC

**Comment by macdonaldtomw** [comment] 2018-10-30 15:48
Okay, but how do I disable tree-sitter?
