### ISSUE TITLE
Highlighting broke in all many languages

### ISSUE THREAD

**Issue by mlangiu** [atom/language-todo#92] opened 2018-11-23 14:05 UTC
### Prerequisites

* [x] I have done all of the following:
    * Reproduced in safe-mode
    * Checked that my issue isn't already filed:

### Description

I guess the title says all, you can use the test comments below to check if this is the case for you
```
# FIXME: Python, Shell Script, Ruby don't work but CoffeScript and YAML do

// FIXME: C and C++ don't work but C# and Java do

; FIXME: Clojure works

/*  */  FIXME: CSS highlights all of this 
/* FIXME: This is highlighted as expected in CSS*/


<!--  FIXME: Html doesn't work, but Markdown does -->
```

### Steps to Reproduce

1. Open file
2. Set language
3. Write special comment in language

**Expected behavior:** [What you expect to happen]

Comments starting with TODO, FIXME, BUG, etc. should be highlighted

**Actual behavior:** [What actually happens]

In some languages highlighting fails

**Reproduces how often:** [What percentage of the time does it reproduce?]

Consistently

### Versions

OS: macOS Sierra

Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.2
python 2.7.15
git 2.14.3

**Comment by thomasjo** [comment] 2018-11-23 15:42
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #82. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by thomasjo** 2018-11-23 15:42 UTC
