### ISSUE TITLE
Syntax Highlighting Broken in Javascript Files

### ISSUE THREAD

**Issue by jarrodwhitley** [atom/language-todo#96] opened 2019-08-09 18:38 UTC
![Screen Shot 2019-08-09 at 1 21 01 PM](https://user-images.githubusercontent.com/11711674/62800908-2802f580-baaa-11e9-9ae7-bcb48f2bff39.png)
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

TODO, FIXME and the like are not highlight in JS files.

### Steps to Reproduce

1. Open a .js file
2. Add a TODO (ex: // TODO: add element)

**Expected behavior:**

"TODO" should be highlighted

**Actual behavior:**

"TODO" remains the comment color gray.

**Reproduces how often:**

100% of the time

### Versions
OS X 10.14.6
Atom 1.39.1

### Additional Information

- Works fine in other file types like PHP, HTML, and CSS/SCSS

**Comment by rsese** [comment] 2019-08-12 17:47
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/language-todo/issues/82 so you can subscribe there if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-08-12 17:47 UTC
